[workspace]
resolver = "3"
members = ["core/constant","core/crypto","core/data_structures"]

[workspace.package]
version = "1.0.0"
authors = ["Orca <qxbao@github.com>"]
edition = "2024"
repository = "https://github.com/qxbao/coconut"

[workspace.dependencies]
log = "0.4"
env_logger = "0.11.8"
primitive-types = { version = "0.14", features = ["num-traits"] }