[package]
name = "ds"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
primitive-types = { workspace = true }
crypto = { path = "../crypto" }
constant = { path = "../constant" }
serde = { workspace = true }
bincode2 = "2.0.0"
rayon = "1.8"
k256 = "0.13.4"
hex = { workspace = true }
rand_core = "0.9.3"
