[package]
name = "ds"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
log = { workspace = true }
primitive-types = { workspace = true }
crypto = { path = "../crypto" }
constant = { path = "../constant" }
serde = { version = "1.0", features = ["derive"] }
bincode2 = "2.0.0"